# Generated by Django 4.2.2 on 2023-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
